### PR TITLE
Make it work with M1

### PR DESCRIPTION
**Pull request by Plopix**
This PR updates the code to make it work and compile on M1. (Fix: https://github.com/splitsh/lite/issues/61)
Also, it revamps the tests (but still not working)

## Tests

Tests are not correct, ifs were testing the same variable. I revamped a bit but they don't work anymore due to (I guess) the new version of Git. SHA1 is never the same.

## Option

I have never done it, but should we install GoReleaser? And make `splitsh-lite` available via `brew` for all architecture?
But I would need help, as I am a newbie un Go. I don't know if we can compile to Linux, Mac (all Arch) and Windows that easily. And that should be another PR

### CODE REVIEW

**Comment by mbryne** [comment]
I've just spent awhile trying to get that binary compiled locally and am coming up against my own limitations around Go.

@Plopix - is there any possibility you might be able to provide a compiled binary while we wait for this PR to get resolved?

**Comment by instudentmedia** [comment]
Much appreciated @Plopix and noted on security.

**Comment by mbryne** [comment]
Much appreciated @Plopix and noted on security.

**Comment by LukeTowers** [comment]
@fabpot what needs to be done to merge this?

**Comment by Plopix** [comment]
It's still a bit tricky, on the last version of libgit2 1.4 it's not working.

I had to reverse my brew version (sharing the procedure)

```
brew info libgit2
cd "$(brew --repo homebrew/core)"
git log master -- Formula/libgit2.rb
git checkout 54b426b84c8824ae457ae7f654670cc6c30bf46f
brew unlink libgit2
HOMEBREW_NO_AUTO_UPDATE=1 brew install libgit2
```

which makes me think that `go build` is still using a dynamic lib and not a static one.
Still waiting for this I guess to bump a working version for 1.4: https://github.com/libgit2/git2go
https://github.com/libgit2/git2go/issues/899

**Comment by npanau** [comment]
Thanks @Plopix it seems to compil now !

**Comment by vinhha96** [comment]
Hi @Plopix, can you help us to continue processing this PR, please?

**Comment by kdambekalns** [comment]
I was able to build it based on this, with these changes:

- `brew install libgit2` (I didn't have it installed yet)
- dropped the `replace` from `go.mod`
- require `github.com/libgit2/git2go/v34 v34.0.0` in `go.mod`
- import `git "github.com/libgit2/git2go/v34"` (added the `/v34` suffix)

with that I could build it using just `go build -o splitsh-lite`

**Comment by Plopix** [comment]
`libgit2/git2go` v34 has been released yesterday! compliant with the last libgit2 `1.5`

I have updated the code(thanks @kdambekalns ) no more need to compile anything statically, it just works now.

Would love something to test that on Linux maybe and then it might be mergeable @fabpot  ;-)

**Comment by npanau** [comment]
> `libgit2/git2go` v34 has been released yesterday! compliant with the last libgit2 `1.5`
> 
> I have updated the code(thanks @kdambekalns ) no more need to compile anything statically, it just works now.
> 


Hello @Plopix ; i've recently update to Ventura; i've tried to compile your fork but I can't get it to work 😬 
(I did have libgit2 `1.5`)
Can you please give me a clue / steps to follow to try to compile it ?
Many thanks

**Comment by kdambekalns** [comment]
> I was able to build it based on this, with these changes:
> 
>     * `brew install libgit2` (I didn't have it installed yet)

That needs to be `brew install libgit2@1.5` nowadays, as otherwise you'll get a newer version. And with that `git2go` is not compatible, leading to `Invalid libgit2 version; this git2go supports libgit2 between v1.5.0 and v1.5.0`

>     * dropped the `replace` from `go.mod`
>     * require `github.com/libgit2/git2go/v34 v34.0.0` in `go.mod`
>     * import `git "github.com/libgit2/git2go/v34"` (added the `/v34` suffix)
> 
> with that I could build it using just `go build -o splitsh-lite`

But not anymore. Now it needs some environment variables on top to ue the "keg-only" `libgit2@v1.5`:

```
export LDFLAGS="-L/opt/homebrew/opt/libgit2@1.5/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libgit2@1.5/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/libgit2@1.5/lib/pkgconfig"
go build -o splitsh-lite
```

**Comment by fabpot** [comment]
Closing in favor of #69

**Pull request closed without merging**
