### PR TITLE
Initiated and tided go mod

### PR DESCRIPTION
**Pull request by spolischook**
It is something like a composer in a Go world
https://blog.golang.org/using-go-modules

### CODE REVIEW

**Comment by spolischook** [comment]
I don't this it's a good solution to tie library to the concrete implementation of libgit2, but I don't understand how it could work without go.mod either. I have no much experience here.

**Comment by spolischook** [comment]
I don't know what to do with this.
Please, use your supperpower to close it or continue by comment.

**Comment by spolischook** [comment]
> If you have projects that do not build in module-aware mode, now is the time to migrate.
https://go.dev/blog/go116-module-changes 
cc @fabpot

**Comment by kdambekalns** [comment]
This is included in #66, so it could be closed…

**Pull request closed without merging**
